name: Publish Python Package to PyPI

on:
  push:
    tags:
      - 'v*' # Trigger the workflow on version tags like v0.1.0

jobs:
  build-and-publish:
    name: Build and publish Python distributions to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for trusted publishing

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build dependencies
        run: python -m pip install build twine

      - name: Build package
        run: python -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # You will need to generate a PyPI API token and store it as a secret
          # in your GitHub repository settings.
          password: ${{ secrets.PYPI_API_TOKEN }}

